name: Build EXE and Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install Flask pandas matplotlib openpyxl xhtml2pdf pywebview
      - name: Build executable
        shell: powershell
        run: ./build-scripts/build_exe.ps1
      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --no-progress -y
      - name: Build installer
        shell: powershell
        run: iscc build-scripts/installer.iss
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ultrasuite
          path: |
            dist/ultrasuite-server.exe
            dist/ultrasuite-gui.exe
            installer/ultrasuite-setup.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            dist/ultrasuite-server.exe
            dist/ultrasuite-gui.exe
            installer/ultrasuite-setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
